### ISSUE TITLE
[BUG] Cannot see tooltip after next build Next.js 13 `TypeError: f is not a function`

### ISSUE THREAD

**Issue by the-new-kai-lu** [ReactTooltip/react-tooltip#1001]
**Describe the bug**
Tooltips do not show in NextJS

**Version of Package**
v5.10.5

**To Reproduce**
Create a project with the latest version of Next (v13), and add a tooltip to a component with anchor-select. 
Run `npm run build` then `npm run start`. The tooltip won't show (in a previous version, the component crashed the entire site)

**Expected behavior**
The tooltip should show.

**Desktop (please complete the following information if possible or delete this section):**
 - OS: Windows
 - Chrome
 - 111.0.5563.147
 - Frameworks NextJS 13

**Additional context**
This problem cannot be replicated with `npm run dev`; the tooltip works fine in dev.

**Comment by thobiasn** [comment]
We are experiencing this exact issue aswell.

**Comment by evgeniy28** [comment]
I fix this problem only downgrade react-tooltip:
```diff
"next": "13.1.5",
"react": "18.2.0",
"react-dom": "18.2.0",
- "react-tooltip": "5.10.5",
+ "react-tooltip": "5.8.3",
```

**Comment by gabrieljablonski** [comment]
I am unable to reproduce this issue where the build completes but the tooltip doesn't show, but it might be related to what @thobiasn reported.

> We are experiencing this exact issue aswell. We are getting the following error, which can hopefully help?
> `Uncaught (in promise) TypeError: f is not a function`

Please try upgrading to the latest `next@beta` version (`next@13.2.5-canary.30` at the time of writing).
This is caused by an issue with Next.js bundler, and theres not much we can do on our end.

**Comment by thobiasn** [comment]
> I fix this problem only downgrade react-tooltip:
> 
> ```diff
> "next": "13.1.5",
> "react": "18.2.0",
> "react-dom": "18.2.0",
> - "react-tooltip": "5.10.5",
> + "react-tooltip": "5.8.3",
> ```

This solved the issue for us aswell.

**Comment by thathurtabit** [comment]
Should this have been closed?

**Comment by gabrieljablonski** [comment]
We'll leave this open for reference if other people run into it, but as of right now this is a won't fix.

The two alternatives are upgrading Next.js to on of the more recent beta release, or downgrading `react-tooltip` to 5.8.3.

Whenever Next.js has a stable release with the fix, we'll close this and maybe add a troubleshoot section to the readme mentioning this.

**Comment by danielbarion** [comment]
Hi, can you guys try the latest stable Next.js release, please? `v13.3.0`

**Comment by gabrieljablonski** [comment]
> Hi, can you guys try the latest stable Next.js release, please? `v13.3.0`

Tested on a new project with `next@13.3.0` and they seem to have fixed it.

**Comment by cat-in-a-box** [comment]
Can confirm, works well on nextjs@13.3.0, no such error on stable release

**Comment by gabrieljablonski** [comment]
We now have a [troubleshooting page in the docs](https://react-tooltip.com/docs/troubleshooting#nextjs-typeerror-f-is-not-a-function), and also a [README section](https://github.com/ReactTooltip/react-tooltip#nextjs-typeerror-f-is-not-a-function) covering this.

**Comment by ryanwoconnor** [comment]
Upgrade to 13.3.0 resolved this for me as well. I did not need to downgrade react-tooltip. Thank you.
